
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: 'us-east-1'
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}


terraform -chdir=./production/terraform init
terraform -chdir=./production/terraform apply -var "MYSQL_USERNAME=${MYSQL_USERNAME}" -var "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

terraform -chdir=./production/lambda-initdb init
terraform -chdir=./production/lambda-initdb apply -var "MYSQL_USERNAME=${MYSQL_USERNAME}" -var "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
terraform -chdir=./production/lambda-initdb destroy -var "MYSQL_USERNAME=" -var "MYSQL_PASSWORD="

aws eks update-kubeconfig --region us-east-1 --name orderpayments-eks
kubectl apply -f ./production/kubernetes/deployment.yaml 
export MYSQL_HOST=$(aws rds describe-db-instances \
    --region=us-east-1 \
    --db-instance-identifier \
    techchallenge-payment-service \
    --query 'DBInstances[0].Endpoint.Address' \
    --output text)
kubectl set env deployment/payment-deployment \
    SPRING_PROFILE=prd \
    MYSQL_HOST=$MYSQL_HOST \
    MYSQL_PORT=3306 \
    MYSQL_DATABSE=orderpayments \
    MYSQL_USER=$MYSQL_USERNAME \
    MYSQL_PASSWORD=$MYSQL_PASSWORD
