name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven

      - name: Build
        working-directory: ./payment
        run: mvn -B package

      - name: Save Coverage Report
        uses: 'actions/upload-artifact@v4'
        with:
          name: jacoco-report
          path: '${{github.workspace}}/payment/target/site/jacoco/jacoco.xml'

      - name: Add coverage to PR
        id: jacoco
        uses: 'madrapps/jacoco-report@v1.7.1'
        with:
          paths: '${{github.workspace}}/payment/target/site/jacoco/jacoco.xml'
          token: '${{secrets.GITHUB_TOKEN}}'
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Code Coverage

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      - name: Fail PR if overall coverage is less than 80%
        if: ${{steps.jacoco.outputs.coverage-overall < 80.0}}
        uses: 'actions/github-script@v7'
        with:
          script: core.setFailed('Overall coverage <= 80%')

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=pedidos-techallenge_payment-service